### ISSUE TITLE
Minecraft 1.14

### ISSUE THREAD

**Issue by Chaosdave33** [Marekkon5/mmlpi#8]
When I try to start MC 1.14.4 I get an error, that OpenGL can't been found:

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 28.03.20 07:10
Description: Initializing game

java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
	at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:61)
	at cxx.a(SourceFile:130)
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:63)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:996)
	at dbn.<init>(SourceFile:414)
	at net.minecraft.client.main.Main.main(SourceFile:166)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
	at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:61)
	at cxx.a(SourceFile:130)
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:63)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:996)
	at dbn.<init>(SourceFile:414)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (arm) version 4.19.108-v8+
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Server VM (mixed mode), Oracle Corporation
	Memory: 129557232 bytes (123 MB) / 301830144 bytes (287 MB) up to 1060372480 bytes (1011 MB)
	CPUs: 4
	JVM Flags: 5 total; -Xmn128M -Xmx1024M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	Launched Version: 1.15.2
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.system.Library
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: <unknown>

```

**Comment by NikoHD203** [comment]
As you should see in the description, the onliest versions which are available are between the first version of mc and 1.12.2, 1.14 is not supported
